Models/Team.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace aspcoreclass.Models
{
    public class Team 
    {
        public int Id { get; set; }

        [Required]       
        [StringLength(80)]       
        public string Name { get; set; }

        [Range(1890, 2100)]
        public int Founded { get; set; }
    }
}

Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace aspcoreclass.Pages
{
    public class IndexModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

Pages/League/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using aspcoreclass.Models;
using aspcoreclass.Services;

namespace aspcoreclass.Pages
{
    public class CreateModel : PageModel
    {
        private readonly aspcoreclass.Services.TeamDbContext _context;

        public CreateModel(aspcoreclass.Services.TeamDbContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Team Team { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Teams.Add(Team);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

Pages/League/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using aspcoreclass.Models;
using aspcoreclass.Services;

namespace aspcoreclass.Pages
{
    public class DeleteModel : PageModel
    {
        private readonly aspcoreclass.Services.TeamDbContext _context;

        public DeleteModel(aspcoreclass.Services.TeamDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Team Team { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Team = await _context.Teams.FirstOrDefaultAsync(m => m.Id == id);

            if (Team == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Team = await _context.Teams.FindAsync(id);

            if (Team != null)
            {
                _context.Teams.Remove(Team);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

Pages/League/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using aspcoreclass.Models;
using aspcoreclass.Services;

namespace aspcoreclass.Pages
{
    public class DetailsModel : PageModel
    {
        private readonly aspcoreclass.Services.TeamDbContext _context;

        public DetailsModel(aspcoreclass.Services.TeamDbContext context)
        {
            _context = context;
        }

        public Team Team { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Team = await _context.Teams.FirstOrDefaultAsync(m => m.Id == id);

            if (Team == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

Pages/League/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using aspcoreclass.Models;
using aspcoreclass.Services;

namespace aspcoreclass.Pages
{
    public class EditModel : PageModel
    {
        private readonly aspcoreclass.Services.TeamDbContext _context;

        public EditModel(aspcoreclass.Services.TeamDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Team Team { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Team = await _context.Teams.FirstOrDefaultAsync(m => m.Id == id);

            if (Team == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Team).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!TeamExists(Team.Id))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool TeamExists(int id)
        {
            return _context.Teams.Any(e => e.Id == id);
        }
    }
}

Pages/League/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using aspcoreclass.Models;
using aspcoreclass.Services;

namespace aspcoreclass.League.Pages
{
    public class IndexModel : PageModel
    {
        private readonly aspcoreclass.Services.TeamDbContext _context;

        public IndexModel(aspcoreclass.Services.TeamDbContext context)
        {
            _context = context;
        }

        public IList<Team> Team { get;set; }

        public async Task OnGetAsync()
        {
            Team = await _context.Teams.ToListAsync();
        }
    }
}

Pages/League/TestComponent.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace aspcoreclass.Pages.League
{
    public class TestComponentModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

ViewComponents/ListTeamsViewComponent.cs
using aspcoreclass.Services;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace aspcoreclass
{
    public class ListTeamsViewComponent : ViewComponent
    {
        private readonly ITeamData teamData;

        public ListTeamsViewComponent(ITeamData teamData)
        {
            this.teamData = teamData;
        }

        public IViewComponentResult Invoke(string filter)
        {
            var model = teamData.GetAll().Where(t => t.Name.StartsWith(filter));
            return View(model);
        }
    }
}

Pages/Components/ListTeams/Default.cshtml
@model  IEnumerable<aspcoreclass.Models.Team>


<h2>This is the view component</h2>
@foreach(var team in Model)
{
    <div>@team.Name</div>
}

Pages/Index.cshtml
@page
@model aspcoreclass.Pages.IndexModel
@{
    ViewData["Title"] = "Index";
}

<h2>NDC Oslo!</h2>

<a asp-page=".\League\Index">League</a>

Pages/League/Create.cshtml
@page
@model aspcoreclass.Pages.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Team</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Team.Name" class="control-label"></label>
                <input asp-for="Team.Name" class="form-control" />
                <span asp-validation-for="Team.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Team.Founded" class="control-label"></label>
                <input asp-for="Team.Founded" class="form-control" />
                <span asp-validation-for="Team.Founded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/League/Delete.cshtml
@page
@model aspcoreclass.Pages.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Team</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Team.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Team.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Team.Founded)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Team.Founded)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Team.Id" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

Pages/League/Details.cshtml
@page
@model aspcoreclass.Pages.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Team</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Team.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Team.Name)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Team.Founded)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Team.Founded)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Team.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

Pages/League/Edit.cshtml
@page
@model aspcoreclass.Pages.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Team</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Team.Id" />
            <div class="form-group">
                <label asp-for="Team.Name" class="control-label"></label>
                <input asp-for="Team.Name" class="form-control" />
                <span asp-validation-for="Team.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Team.Founded" class="control-label"></label>
                <input asp-for="Team.Founded" class="form-control" />
                <span asp-validation-for="Team.Founded" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Pages/League/Index.cshtml
@page
@model aspcoreclass.League.Pages.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h2>Index</h2>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>                
                @Html.DisplayNameFor(model => model.Team[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Team[0].Founded)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
    @foreach (var item in Model.Team) {
        <partial name="_TeamRecord" model="item" />
    }
    </tbody>
</table>

Pages/League/TestComponent.cshtml
@page
@model aspcoreclass.Pages.League.TestComponentModel


<vc:list-teams filter="S"></vc:list-teams>

Pages/League/_TeamRecord.cshtml
@model aspcoreclass.Models.Team
<tr>
    <td>
        @Html.DisplayFor(m => m.Name)
    </td>
    <td>
        @Html.DisplayFor(m => m.Founded)
    </td>
    <td>
        <a asp-page="./Edit" asp-route-id="@Model.Id">Edit</a> |
        <a asp-page="./Details" asp-route-id="@Model.Id">Details</a> |
        <a asp-page="./Delete" asp-route-id="@Model.Id">Delete</a>
    </td>
</tr>

Pages/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />

    <environment include="Development">
        <link href="~/node_modules/bootstrap/dist/css/bootstrap.css" rel="stylesheet" /> 
    </environment>
    <environment exclude="Development">
        <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" />
    </environment>


    <title>@ViewBag.Title</title>
</head>
<body>
    <div>
        @RenderBody()
    </div>
    @RenderSection("Scripts", false)
</body>
</html>